name: stranger-chat-backend
services:
  - name: backend
    source_dir: /
    github:
      repo: RohanJose/Chat_APP
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: ${CORS_ORIGIN}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
